[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc = "0.8.20"  # Updated to match your Solidity version
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
    '@chainlink/=lib/chainlink/contracts/'
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
